
# Update the list of DTB and DTBOs globally.
KERNEL_DEVICETREE:append:j721e-evm = " \
    ti/k3-j721e-vision-apps.dtbo \
    ti/k3-j721e-edgeai-apps.dtbo \
"
KERNEL_DEVICETREE:append:j721e-hs-evm = " \
    ti/k3-j721e-vision-apps.dtbo \
    ti/k3-j721e-edgeai-apps.dtbo \
"

KERNEL_DEVICETREE:append:j721s2-evm = " \
    ti/k3-j721s2-vision-apps.dtbo \
    ti/k3-j721s2-edgeai-apps.dtbo \
"
KERNEL_DEVICETREE:append:j721s2-hs-evm = " \
    ti/k3-j721s2-vision-apps.dtbo \
    ti/k3-j721s2-edgeai-apps.dtbo \
"

KERNEL_DEVICETREE:append:j784s4-evm = " \
    ti/k3-j784s4-vision-apps.dtbo \
    ti/k3-j784s4-edgeai-apps.dtbo \
"
KERNEL_DEVICETREE:append:j784s4-hs-evm = " \
    ti/k3-j784s4-vision-apps.dtbo \
    ti/k3-j784s4-edgeai-apps.dtbo \
"
